# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cd37af9f7cd5a4e9324eb438f69d571d506d4c2a3e769ca11e8f90d1eeb359d5b5040d2b53b7e3d6aec46a06de04c3d01a25fb6e901f1f71eb62cc92a8a5e0

test:
  secret_key_base: f0cc3bcbe635e4135c03fe12dc5b05262e2ceae025a62656d78b9b154c9a3096ed99190feee6c3aed3b3bd0370b2dfab256a296a38c72ded80a7795b07e5e484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
